/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as ShowSlugRouteImport } from './routes/show.$slug'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as ApiGenerateLinkRouteImport } from './routes/api/generate-link'
import { Route as ApiShowsIndexRouteImport } from './routes/api/shows.index'
import { Route as ApiMoviesIndexRouteImport } from './routes/api/movies.index'
import { Route as AdminShowsIndexRouteImport } from './routes/admin.shows.index'
import { Route as ApiShowsIdRouteImport } from './routes/api/shows.$id'
import { Route as ApiMoviesIdRouteImport } from './routes/api/movies.$id'
import { Route as ApiLoadShowSlugRouteImport } from './routes/api/load-show.$slug'
import { Route as ApiLoadMovieSlugRouteImport } from './routes/api/load-movie.$slug'
import { Route as ApiGoIdRouteImport } from './routes/api/go.$id'
import { Route as ApiFinalIdRouteImport } from './routes/api/final.$id'
import { Route as ApiAdminLinksRouteImport } from './routes/api/admin.links'
import { Route as AdminShowsIdRouteImport } from './routes/admin.shows.$id'
import { Route as AdminMoviesIdRouteImport } from './routes/admin.movies.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowSlugRoute = ShowSlugRouteImport.update({
  id: '/show/$slug',
  path: '/show/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLinkRoute = ApiGenerateLinkRouteImport.update({
  id: '/api/generate-link',
  path: '/api/generate-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShowsIndexRoute = ApiShowsIndexRouteImport.update({
  id: '/api/shows/',
  path: '/api/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesIndexRoute = ApiMoviesIndexRouteImport.update({
  id: '/api/movies/',
  path: '/api/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShowsIndexRoute = AdminShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiShowsIdRoute = ApiShowsIdRouteImport.update({
  id: '/api/shows/$id',
  path: '/api/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesIdRoute = ApiMoviesIdRouteImport.update({
  id: '/api/movies/$id',
  path: '/api/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadShowSlugRoute = ApiLoadShowSlugRouteImport.update({
  id: '/api/load-show/$slug',
  path: '/api/load-show/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadMovieSlugRoute = ApiLoadMovieSlugRouteImport.update({
  id: '/api/load-movie/$slug',
  path: '/api/load-movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoIdRoute = ApiGoIdRouteImport.update({
  id: '/api/go/$id',
  path: '/api/go/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinalIdRoute = ApiFinalIdRouteImport.update({
  id: '/api/final/$id',
  path: '/api/final/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLinksRoute = ApiAdminLinksRouteImport.update({
  id: '/api/admin/links',
  path: '/api/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShowsIdRoute = AdminShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoviesIdRoute = AdminMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/generate-link': typeof ApiGenerateLinkRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/show/$slug': typeof ShowSlugRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/movies/$id': typeof AdminMoviesIdRoute
  '/admin/shows/$id': typeof AdminShowsIdRoute
  '/api/admin/links': typeof ApiAdminLinksRoute
  '/api/final/$id': typeof ApiFinalIdRoute
  '/api/go/$id': typeof ApiGoIdRoute
  '/api/load-movie/$slug': typeof ApiLoadMovieSlugRoute
  '/api/load-show/$slug': typeof ApiLoadShowSlugRoute
  '/api/movies/$id': typeof ApiMoviesIdRoute
  '/api/shows/$id': typeof ApiShowsIdRoute
  '/admin/shows/': typeof AdminShowsIndexRoute
  '/api/movies/': typeof ApiMoviesIndexRoute
  '/api/shows/': typeof ApiShowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-link': typeof ApiGenerateLinkRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/show/$slug': typeof ShowSlugRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/movies/$id': typeof AdminMoviesIdRoute
  '/admin/shows/$id': typeof AdminShowsIdRoute
  '/api/admin/links': typeof ApiAdminLinksRoute
  '/api/final/$id': typeof ApiFinalIdRoute
  '/api/go/$id': typeof ApiGoIdRoute
  '/api/load-movie/$slug': typeof ApiLoadMovieSlugRoute
  '/api/load-show/$slug': typeof ApiLoadShowSlugRoute
  '/api/movies/$id': typeof ApiMoviesIdRoute
  '/api/shows/$id': typeof ApiShowsIdRoute
  '/admin/shows': typeof AdminShowsIndexRoute
  '/api/movies': typeof ApiMoviesIndexRoute
  '/api/shows': typeof ApiShowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/generate-link': typeof ApiGenerateLinkRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/show/$slug': typeof ShowSlugRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/movies/$id': typeof AdminMoviesIdRoute
  '/admin/shows/$id': typeof AdminShowsIdRoute
  '/api/admin/links': typeof ApiAdminLinksRoute
  '/api/final/$id': typeof ApiFinalIdRoute
  '/api/go/$id': typeof ApiGoIdRoute
  '/api/load-movie/$slug': typeof ApiLoadMovieSlugRoute
  '/api/load-show/$slug': typeof ApiLoadShowSlugRoute
  '/api/movies/$id': typeof ApiMoviesIdRoute
  '/api/shows/$id': typeof ApiShowsIdRoute
  '/admin/shows/': typeof AdminShowsIndexRoute
  '/api/movies/': typeof ApiMoviesIndexRoute
  '/api/shows/': typeof ApiShowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/generate-link'
    | '/movie/$slug'
    | '/show/$slug'
    | '/verify/$id'
    | '/admin/'
    | '/admin/movies/$id'
    | '/admin/shows/$id'
    | '/api/admin/links'
    | '/api/final/$id'
    | '/api/go/$id'
    | '/api/load-movie/$slug'
    | '/api/load-show/$slug'
    | '/api/movies/$id'
    | '/api/shows/$id'
    | '/admin/shows/'
    | '/api/movies/'
    | '/api/shows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate-link'
    | '/movie/$slug'
    | '/show/$slug'
    | '/verify/$id'
    | '/admin'
    | '/admin/movies/$id'
    | '/admin/shows/$id'
    | '/api/admin/links'
    | '/api/final/$id'
    | '/api/go/$id'
    | '/api/load-movie/$slug'
    | '/api/load-show/$slug'
    | '/api/movies/$id'
    | '/api/shows/$id'
    | '/admin/shows'
    | '/api/movies'
    | '/api/shows'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/generate-link'
    | '/movie/$slug'
    | '/show/$slug'
    | '/verify/$id'
    | '/admin/'
    | '/admin/movies/$id'
    | '/admin/shows/$id'
    | '/api/admin/links'
    | '/api/final/$id'
    | '/api/go/$id'
    | '/api/load-movie/$slug'
    | '/api/load-show/$slug'
    | '/api/movies/$id'
    | '/api/shows/$id'
    | '/admin/shows/'
    | '/api/movies/'
    | '/api/shows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiGenerateLinkRoute: typeof ApiGenerateLinkRoute
  MovieSlugRoute: typeof MovieSlugRoute
  ShowSlugRoute: typeof ShowSlugRoute
  VerifyIdRoute: typeof VerifyIdRoute
  ApiAdminLinksRoute: typeof ApiAdminLinksRoute
  ApiFinalIdRoute: typeof ApiFinalIdRoute
  ApiGoIdRoute: typeof ApiGoIdRoute
  ApiLoadMovieSlugRoute: typeof ApiLoadMovieSlugRoute
  ApiLoadShowSlugRoute: typeof ApiLoadShowSlugRoute
  ApiMoviesIdRoute: typeof ApiMoviesIdRoute
  ApiShowsIdRoute: typeof ApiShowsIdRoute
  ApiMoviesIndexRoute: typeof ApiMoviesIndexRoute
  ApiShowsIndexRoute: typeof ApiShowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$slug': {
      id: '/show/$slug'
      path: '/show/$slug'
      fullPath: '/show/$slug'
      preLoaderRoute: typeof ShowSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-link': {
      id: '/api/generate-link'
      path: '/api/generate-link'
      fullPath: '/api/generate-link'
      preLoaderRoute: typeof ApiGenerateLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shows/': {
      id: '/api/shows/'
      path: '/api/shows'
      fullPath: '/api/shows/'
      preLoaderRoute: typeof ApiShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/': {
      id: '/api/movies/'
      path: '/api/movies'
      fullPath: '/api/movies/'
      preLoaderRoute: typeof ApiMoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shows/': {
      id: '/admin/shows/'
      path: '/shows'
      fullPath: '/admin/shows/'
      preLoaderRoute: typeof AdminShowsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/shows/$id': {
      id: '/api/shows/$id'
      path: '/api/shows/$id'
      fullPath: '/api/shows/$id'
      preLoaderRoute: typeof ApiShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies/$id': {
      id: '/api/movies/$id'
      path: '/api/movies/$id'
      fullPath: '/api/movies/$id'
      preLoaderRoute: typeof ApiMoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/load-show/$slug': {
      id: '/api/load-show/$slug'
      path: '/api/load-show/$slug'
      fullPath: '/api/load-show/$slug'
      preLoaderRoute: typeof ApiLoadShowSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/load-movie/$slug': {
      id: '/api/load-movie/$slug'
      path: '/api/load-movie/$slug'
      fullPath: '/api/load-movie/$slug'
      preLoaderRoute: typeof ApiLoadMovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/go/$id': {
      id: '/api/go/$id'
      path: '/api/go/$id'
      fullPath: '/api/go/$id'
      preLoaderRoute: typeof ApiGoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/final/$id': {
      id: '/api/final/$id'
      path: '/api/final/$id'
      fullPath: '/api/final/$id'
      preLoaderRoute: typeof ApiFinalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/links': {
      id: '/api/admin/links'
      path: '/api/admin/links'
      fullPath: '/api/admin/links'
      preLoaderRoute: typeof ApiAdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shows/$id': {
      id: '/admin/shows/$id'
      path: '/shows/$id'
      fullPath: '/admin/shows/$id'
      preLoaderRoute: typeof AdminShowsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movies/$id': {
      id: '/admin/movies/$id'
      path: '/movies/$id'
      fullPath: '/admin/movies/$id'
      preLoaderRoute: typeof AdminMoviesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMoviesIdRoute: typeof AdminMoviesIdRoute
  AdminShowsIdRoute: typeof AdminShowsIdRoute
  AdminShowsIndexRoute: typeof AdminShowsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminMoviesIdRoute: AdminMoviesIdRoute,
  AdminShowsIdRoute: AdminShowsIdRoute,
  AdminShowsIndexRoute: AdminShowsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiGenerateLinkRoute: ApiGenerateLinkRoute,
  MovieSlugRoute: MovieSlugRoute,
  ShowSlugRoute: ShowSlugRoute,
  VerifyIdRoute: VerifyIdRoute,
  ApiAdminLinksRoute: ApiAdminLinksRoute,
  ApiFinalIdRoute: ApiFinalIdRoute,
  ApiGoIdRoute: ApiGoIdRoute,
  ApiLoadMovieSlugRoute: ApiLoadMovieSlugRoute,
  ApiLoadShowSlugRoute: ApiLoadShowSlugRoute,
  ApiMoviesIdRoute: ApiMoviesIdRoute,
  ApiShowsIdRoute: ApiShowsIdRoute,
  ApiMoviesIndexRoute: ApiMoviesIndexRoute,
  ApiShowsIndexRoute: ApiShowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
